#!/usr/bin/env bash
set -euo pipefail

SESSION_NAME="${SESSION_NAME:-searchqa_env}"
PORT="${PORT:-36015}"
GPU_ID="${GPU_ID:-2}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
SEARCHQA_ENV_CONDA_PREFIX="${SEARCHQA_ENV_CONDA_PREFIX:-${REPO_ROOT}/.venv}"
SEARCHQA_SERVER_BIN="${SEARCHQA_SERVER_BIN:-${SEARCHQA_ENV_CONDA_PREFIX}/bin/searchqa}"

export CUDA_VISIBLE_DEVICES="${GPU_ID}"

# Local service should never use inherited proxies.
unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY
export no_proxy="127.0.0.1,localhost"
export NO_PROXY="127.0.0.1,localhost"

export SEARCHQA_RETRIEVAL_METHOD="${SEARCHQA_RETRIEVAL_METHOD:-e5}"
export SEARCHQA_FAISS_GPU="${SEARCHQA_FAISS_GPU:-false}"
export SEARCHQA_FAISS_GPU_TEMP_MEMORY="${SEARCHQA_FAISS_GPU_TEMP_MEMORY:-268435456}"
export SEARCHQA_RETRIEVAL_USE_FP16="${SEARCHQA_RETRIEVAL_USE_FP16:-true}"
export SEARCHQA_RETRIEVAL_BATCH_SIZE="${SEARCHQA_RETRIEVAL_BATCH_SIZE:-128}"
export SEARCHQA_BATCHED_RETRIEVAL="${SEARCHQA_BATCHED_RETRIEVAL:-true}"
export SEARCHQA_SEARCH_BATCH_SIZE="${SEARCHQA_SEARCH_BATCH_SIZE:-32}"
export SEARCHQA_SEARCH_BATCH_MAX_WAIT_MS="${SEARCHQA_SEARCH_BATCH_MAX_WAIT_MS:-20}"
export SEARCHQA_SEARCH_RESULT_TIMEOUT_S="${SEARCHQA_SEARCH_RESULT_TIMEOUT_S:-300}"
export SEARCHQA_SEARCH_QUEUE_SIZE="${SEARCHQA_SEARCH_QUEUE_SIZE:-512}"
export SEARCHQA_THREADPOOL_TOKENS="${SEARCHQA_THREADPOOL_TOKENS:-256}"

LOG_FILE="${LOG_FILE:-/tmp/searchqa_env_${PORT}.log}"

tmux kill-session -t "${SESSION_NAME}" 2>/dev/null || true
tmux new-session -d -s "${SESSION_NAME}" "\
  export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}; \
  unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY; \
  export no_proxy='127.0.0.1,localhost'; \
  export NO_PROXY='127.0.0.1,localhost'; \
  export SEARCHQA_RETRIEVAL_METHOD=${SEARCHQA_RETRIEVAL_METHOD}; \
  export SEARCHQA_FAISS_GPU=${SEARCHQA_FAISS_GPU}; \
  export SEARCHQA_FAISS_GPU_TEMP_MEMORY=${SEARCHQA_FAISS_GPU_TEMP_MEMORY}; \
  export SEARCHQA_RETRIEVAL_USE_FP16=${SEARCHQA_RETRIEVAL_USE_FP16}; \
  export SEARCHQA_RETRIEVAL_BATCH_SIZE=${SEARCHQA_RETRIEVAL_BATCH_SIZE}; \
  export SEARCHQA_BATCHED_RETRIEVAL=${SEARCHQA_BATCHED_RETRIEVAL}; \
  export SEARCHQA_SEARCH_BATCH_SIZE=${SEARCHQA_SEARCH_BATCH_SIZE}; \
  export SEARCHQA_SEARCH_BATCH_MAX_WAIT_MS=${SEARCHQA_SEARCH_BATCH_MAX_WAIT_MS}; \
  export SEARCHQA_SEARCH_RESULT_TIMEOUT_S=${SEARCHQA_SEARCH_RESULT_TIMEOUT_S}; \
  export SEARCHQA_SEARCH_QUEUE_SIZE=${SEARCHQA_SEARCH_QUEUE_SIZE}; \
  export SEARCHQA_THREADPOOL_TOKENS=${SEARCHQA_THREADPOOL_TOKENS}; \
  ${SEARCHQA_SERVER_BIN} --host 127.0.0.1 --port ${PORT} 2>&1 | tee ${LOG_FILE}"

echo "Started SearchQA env server in tmux session ${SESSION_NAME} on port ${PORT}"
echo "Server bin: ${SEARCHQA_SERVER_BIN}"
echo "FAISS GPU: ${SEARCHQA_FAISS_GPU} visible GPUs: ${CUDA_VISIBLE_DEVICES}"
echo "Log: ${LOG_FILE}"
